spring:
  application:
    name: spring-3-fundamental
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: spring_svc
    password: 123456
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
